logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG

spring:
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        hbm2ddl:
          auto: update
  datasource:
    username: s336704
    password: 2mcymbRttDTo9PIf
    url: jdbc:postgresql://pg:5432/studs
server:
  port : 34101

security:
  basic:
    enabled: false

jwt:
  private.key: classpath:app.key
  public.key: classpath:app.pub

token:
  bearer.expiration: 86400 # 24 hours
