version: '3.9'
services:
  postgres:
    image: postgres
    container_name: lab4-postgresql
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=lab4
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres:/var/lib/postgesql/data
    restart: always
    networks:
      - postgres

  app:
    build: ../
    container_name: lab4-app
    ports:
      - "8080:8080"
    environment:
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=lab4
      - DB_HOST=postgres
      - SERVER_PORT=8080
      - spring_profiles_active=dev
    networks:
      - postgres
    depends_on:
      - postgres

volumes:
  postgres:

networks:
  postgres:
    driver: bridge