on:
  push:
    paths:
      - 'pom.xml'
      - '.github/workflows/**'
      - 'src/**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set Up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Build Jar
        run: mvn package
      - name: Save Artifact
        uses: actions/upload-artifact@v3
        with:
          name: app-artifact
          path: target/Lab4-0.0.1-SNAPSHOT.jar

  push-image:
    runs-on: ubuntu-latest
    needs: [ build ]
    steps:
      - name: Fetch Artifact
        uses: actions/download-artifact@v3
        with:
          name: app-artifact
          path: app.jar
      - name: See files
        run: ls -la
      - name: Build Image
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/web-lab-4:latest .
      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Push image
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/web-lab-4:latest
